version: "1.0"

services:
  auth-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment

  pay-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment

  email-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment

  sms-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment


networks:
  payment: