version: "1.0"

services:

  kong:
    image: kong
    volumes:
      - "volumeName:containerPath:ro"
    environment:
      - KONG_DATABASE=postgres
        KONG_PG_HOST=database
        KONG_PG_PASSWORD=kongpass
        KONG_PASSWORD=test

  auth-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment

  pay-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment

  email-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment

  sms-service:
    ports:
      - "8080:80"
    build:
      context: contextPath
      dockerfile: Dockerfile
    networks:
      - payment


networks:
  payment: